### ISSUE TITLE
ARM Image?

### ISSUE THREAD

**Issue by threehappypenguins** [bertmelis/immich-machine-learning-no-avx#2]
I have an Odroid HC2, ran the command `grep -E 'avx2?' /proc/cpuinfo` and don't see AVX. Any plans to support ARM architechture?

**Comment by bertmelis** [comment]
Doesn't it work with the official Immich images? --> https://hub.docker.com/r/altran1502/immich-machine-learning/tags
Or is it a 32-bit system?

**Comment by threehappypenguins** [comment]
Yes, it's armv7, so 32-bit.

**Comment by bertmelis** [comment]
So, immich itself provides a armv7 image. Did you try it?

**Comment by threehappypenguins** [comment]
Yes, it's running right now. But without the machine learning. I'm just asking about having a machine learning image with no avx requirements for armv7.

**Comment by bertmelis** [comment]
But the machine-learning image is also available for armv7: https://hub.docker.com/r/altran1502/immich-machine-learning/tags

Why wouldn't it work?

PS Tensorflow has published a guide themselves to build: https://www.tensorflow.org/lite/guide/build_cmake_arm

**Comment by threehappypenguins** [comment]
I can't install that one as per the instructions: https://immich.app/docs/install/requirements

I do not have avx or avx2 instruction sets.

**Comment by bertmelis** [comment]
I would try it at least. I'd say that part of the docs is not up-to-date. Tensorflow for x86 does require AVX indeed, but this requirement is only for x86 processors. ARM is a different beast.

**Comment by threehappypenguins** [comment]
Ohhhh. That makes sense. Thanks for clarifying! I just didn't even both running the container because of the docs. In any case, I will revisit this at a later time, hopefully if the dev adds the ability to import, and library files staying separate from the media folder(s). Then I'm sold on Immich. :)
